IF OBJECT_ID('demo.APP_EXCEPTION_LOG') IS NULL
BEGIN
	CREATE TABLE demo.APP_EXCEPTION_LOG(
		LogId INT IDENTITY(1,1) PRIMARY KEY,
		ExceptionMessage NVARCHAR(MAX),
		SourceMethod NVARCHAR(MAX),
		StackTrace NVARCHAR(MAX),
		LastModifiedDate DATETIME2 DEFAULT SYSUTCDATETIME()
	);
END;